// seed/seedExercises.js
//
// Seeds the Exercise collection with a comprehensive library covering
// every muscleGroup + equipment type defined in models/Exercise.js.
//
// USAGE:
//   node seed/seedExercises.js            -> upsert (safe, re-runnable, won't touch other data)
//   node seed/seedExercises.js --fresh    -> wipes the Exercise collection first, then inserts
//
// Make sure MONGO_URI is set in your .env (adjust the env var name below
// if your project uses a different one, e.g. MONGODB_URI / DB_URI).

import mongoose from "mongoose";
import dotenv from "dotenv";
import Exercise from "../models/Exercise.js";

dotenv.config();

const exercises = [
  // ============================================================
  // CHEST
  // ============================================================
  {
    name: "Barbell Bench Press",
    muscleGroup: "Chest",
    secondaryMuscles: ["Triceps", "Shoulders"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    exerciseType: "Compound",
    instructions: "Lie flat on a bench, grip the bar slightly wider than shoulder-width, lower it to mid-chest, then press back up to full arm extension.",
    commonMistakes: "Flaring elbows too wide, bouncing the bar off the chest, lifting hips off the bench.",
    tips: "Keep shoulder blades retracted and drive through your feet for stability.",
  },
  {
    name: "Incline Barbell Bench Press",
    muscleGroup: "Chest",
    secondaryMuscles: ["Shoulders", "Triceps"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    exerciseType: "Compound",
    instructions: "On a 30-45 degree incline bench, lower the bar to your upper chest, then press it back up to full extension.",
    commonMistakes: "Setting the incline too steep, turning it into a shoulder press.",
    tips: "A moderate incline keeps tension on the upper chest without over-recruiting the front delts.",
  },
  {
    name: "Decline Barbell Bench Press",
    muscleGroup: "Chest",
    secondaryMuscles: ["Triceps"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    exerciseType: "Compound",
    instructions: "On a decline bench, lower the bar to your lower chest, then press back up to full extension.",
    commonMistakes: "Lowering the bar too high on the chest, losing footing on the decline bench.",
    tips: "Secure your legs under the pads before unracking the bar.",
  },
  {
    name: "Flat Dumbbell Bench Press",
    muscleGroup: "Chest",
    secondaryMuscles: ["Shoulders", "Triceps"],
    equipment: "Dumbbell",
    difficulty: "Intermediate",
    exerciseType: "Compound",
    instructions: "Lie on a flat bench holding dumbbells above your chest, lower them to the sides of your chest, then press back up.",
    commonMistakes: "Letting the dumbbells drift too far apart, using a limited range of motion.",
    tips: "Dumbbells allow a deeper stretch at the bottom than a barbell — use it.",
  },
  {
    name: "Incline Dumbbell Press",
    muscleGroup: "Chest",
    secondaryMuscles: ["Shoulders", "Triceps"],
    equipment: "Dumbbell",
    difficulty: "Intermediate",
    exerciseType: "Compound",
    instructions: "Set a bench to a 30-45 degree incline. Press dumbbells from shoulder level to full extension above the chest, then lower under control.",
    commonMistakes: "Setting the incline too steep, which shifts emphasis to shoulders.",
    tips: "Rotate palms slightly inward at the top to fully engage the upper chest.",
  },
  {
    name: "Decline Dumbbell Press",
    muscleGroup: "Chest",
    secondaryMuscles: ["Triceps"],
    equipment: "Dumbbell",
    difficulty: "Intermediate",
    exerciseType: "Compound",
    instructions: "On a decline bench, press dumbbells from chest level to full extension above your lower chest, then lower with control.",
    commonMistakes: "Rushing the setup, letting the dumbbells drift backward toward the face.",
    tips: "Have a spotter help hand you the dumbbells at the start.",
  },
  {
    name: "Dumbbell Fly",
    muscleGroup: "Chest",
    secondaryMuscles: ["Shoulders"],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Lie on a flat bench with dumbbells above your chest, arms slightly bent, lower them out to the sides in an arc, then bring them back together.",
    commonMistakes: "Bending the elbows too much and turning it into a press, going too heavy and straining the shoulder.",
    tips: "Imagine hugging a large barrel to keep the arc smooth and controlled.",
  },
  {
    name: "Incline Dumbbell Fly",
    muscleGroup: "Chest",
    secondaryMuscles: ["Shoulders"],
    equipment: "Dumbbell",
    difficulty: "Intermediate",
    exerciseType: "Isolation",
    instructions: "On an incline bench, lower dumbbells out to the sides in a wide arc, then bring them back together above your upper chest.",
    commonMistakes: "Lowering too far and straining the shoulder joint.",
    tips: "Keep a slight, fixed bend in your elbows throughout the movement.",
  },
  {
    name: "Cable Fly",
    muscleGroup: "Chest",
    secondaryMuscles: ["Shoulders"],
    equipment: "Cable",
    difficulty: "Intermediate",
    exerciseType: "Isolation",
    instructions: "Stand between two cable towers, arms slightly bent. Bring the handles together in a wide arc in front of your chest, then return slowly.",
    commonMistakes: "Using momentum, bending elbows too much and turning it into a press.",
    tips: "Focus on squeezing the chest at the point where hands meet.",
  },
  {
    name: "Low-to-High Cable Fly",
    muscleGroup: "Chest",
    secondaryMuscles: ["Shoulders"],
    equipment: "Cable",
    difficulty: "Intermediate",
    exerciseType: "Isolation",
    instructions: "Set pulleys to the lowest position, sweep the handles upward and inward in an arc to meet above your chest, then return with control.",
    commonMistakes: "Using the arms to pull instead of the pecs, standing too far from the cable stack.",
    tips: "This angle emphasizes the upper chest — squeeze hard at the top.",
  },
  {
    name: "High-to-Low Cable Fly",
    muscleGroup: "Chest",
    secondaryMuscles: ["Shoulders"],
    equipment: "Cable",
    difficulty: "Intermediate",
    exerciseType: "Isolation",
    instructions: "Set pulleys to the highest position, sweep the handles downward and inward in an arc to meet in front of your hips, then return with control.",
    commonMistakes: "Leaning too far forward, using momentum to yank the handles down.",
    tips: "This angle biases the lower chest fibers.",
  },
  {
    name: "Machine Chest Press",
    muscleGroup: "Chest",
    secondaryMuscles: ["Triceps", "Shoulders"],
    equipment: "Machine",
    difficulty: "Beginner",
    exerciseType: "Compound",
    instructions: "Sit with back flat against the pad, grip handles at chest height, and press forward to full extension before returning slowly.",
    commonMistakes: "Not adjusting seat height, causing handles to sit too high or low.",
    tips: "Great option for controlled overload without needing a spotter.",
  },
  {
    name: "Pec Deck Fly",
    muscleGroup: "Chest",
    secondaryMuscles: ["Shoulders"],
    equipment: "Machine",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Sit with back against the pad, forearms on the arm pads, bring them together in front of your chest, then return slowly under control.",
    commonMistakes: "Slamming the pads together, using too much weight and shortening the range of motion.",
    tips: "Pause and squeeze at full contraction for a stronger peak.",
  },
  {
    name: "Push-Up",
    muscleGroup: "Chest",
    secondaryMuscles: ["Triceps", "Core", "Shoulders"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    exerciseType: "Compound",
    instructions: "Start in a plank position, hands under shoulders. Lower your chest to the floor, then push back up while keeping your body straight.",
    commonMistakes: "Sagging hips, flaring elbows, incomplete range of motion.",
    tips: "Squeeze glutes and core to keep a rigid plank throughout.",
  },
  {
    name: "Weighted Dip",
    muscleGroup: "Chest",
    secondaryMuscles: ["Triceps", "Shoulders"],
    equipment: "Bodyweight",
    difficulty: "Advanced",
    exerciseType: "Compound",
    instructions: "Support yourself on parallel bars with added weight via a belt, lower your body by bending elbows until shoulders are below elbows, then press back up.",
    commonMistakes: "Going too deep and straining the shoulder joint, excessive forward lean turning it into a triceps-only move.",
    tips: "Lean forward slightly to bias the chest over the triceps.",
  },
  {
    name: "Smith Machine Bench Press",
    muscleGroup: "Chest",
    secondaryMuscles: ["Triceps", "Shoulders"],
    equipment: "Smith Machine",
    difficulty: "Beginner",
    exerciseType: "Compound",
    instructions: "Lie on a bench under the fixed bar path, unrack the bar, lower it to your chest, then press back up along the guided track.",
    commonMistakes: "Positioning the bench too far forward or back relative to the bar path.",
    tips: "Useful for training close to failure safely without a spotter.",
  },

  // ============================================================
  // BACK
  // ============================================================
  {
    name: "Conventional Deadlift",
    muscleGroup: "Back",
    secondaryMuscles: ["Glutes", "Legs", "Forearms", "Core"],
    equipment: "Barbell",
    difficulty: "Advanced",
    exerciseType: "Compound",
    instructions: "Stand with feet hip-width apart, grip the bar outside your knees, brace your core, and drive through your heels to stand up tall, keeping the bar close to your body.",
    commonMistakes: "Rounding the lower back, letting the bar drift away from the shins.",
    tips: "Think 'push the floor away' rather than 'pull the bar up'.",
  },
  {
    name: "Sumo Deadlift",
    muscleGroup: "Back",
    secondaryMuscles: ["Glutes", "Legs", "Forearms"],
    equipment: "Barbell",
    difficulty: "Advanced",
    exerciseType: "Compound",
    instructions: "Stand with a wide stance, toes pointed out, grip the bar inside your knees, and drive up by pushing your knees out and hips forward.",
    commonMistakes: "Knees caving inward, rounding the upper back.",
    tips: "Push your knees out in the direction of your toes throughout the pull.",
  },
  {
    name: "Rack Pull",
    muscleGroup: "Back",
    secondaryMuscles: ["Glutes", "Forearms"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    exerciseType: "Compound",
    instructions: "Set the bar on safety pins just below knee height, grip it, and pull to full lockout by extending hips and knees together.",
    commonMistakes: "Using too much weight and relying on the lower back instead of hips.",
    tips: "A great overload movement for building upper back and grip strength.",
  },
  {
    name: "Pull-Up",
    muscleGroup: "Back",
    secondaryMuscles: ["Biceps", "Forearms", "Core"],
    equipment: "Bodyweight",
    difficulty: "Advanced",
    exerciseType: "Compound",
    instructions: "Hang from a bar with an overhand grip, pull your chin above the bar by driving elbows down, then lower with control.",
    commonMistakes: "Using momentum or kipping, not achieving full range of motion.",
    tips: "Focus on pulling with your elbows, not your hands.",
  },
  {
    name: "Chin-Up",
    muscleGroup: "Back",
    secondaryMuscles: ["Biceps", "Forearms"],
    equipment: "Bodyweight",
    difficulty: "Advanced",
    exerciseType: "Compound",
    instructions: "Hang from a bar with an underhand grip, pull yourself up until your chin clears the bar, then lower with control.",
    commonMistakes: "Not achieving a full stretch at the bottom, swinging the legs.",
    tips: "The underhand grip recruits more biceps than a standard pull-up.",
  },
  {
    name: "Wide-Grip Lat Pulldown",
    muscleGroup: "Back",
    secondaryMuscles: ["Biceps", "Forearms"],
    equipment: "Cable",
    difficulty: "Beginner",
    exerciseType: "Compound",
    instructions: "Grip the bar wider than shoulder-width, pull it down to your upper chest while leaning back slightly, then control it back up.",
    commonMistakes: "Pulling behind the neck, using excessive body swing.",
    tips: "Drive elbows down and back rather than just pulling with the arms.",
  },
  {
    name: "Close-Grip Lat Pulldown",
    muscleGroup: "Back",
    secondaryMuscles: ["Biceps", "Forearms"],
    equipment: "Cable",
    difficulty: "Beginner",
    exerciseType: "Compound",
    instructions: "Using a close, neutral-grip handle, pull it down toward your chest while keeping your torso upright, then control it back up.",
    commonMistakes: "Leaning back excessively to move more weight.",
    tips: "This grip allows a deeper contraction of the lower lats.",
  },
  {
    name: "Straight-Arm Pulldown",
    muscleGroup: "Back",
    secondaryMuscles: ["Triceps"],
    equipment: "Cable",
    difficulty: "Intermediate",
    exerciseType: "Isolation",
    instructions: "Stand facing a high cable, arms straight, pull the bar down toward your thighs in an arc, then let it return under control.",
    commonMistakes: "Bending the elbows and turning it into a pushdown.",
    tips: "Keep a slight, fixed bend in the elbows and move from the shoulder joint only.",
  },
  {
    name: "Barbell Bent-Over Row",
    muscleGroup: "Back",
    secondaryMuscles: ["Biceps", "Forearms"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    exerciseType: "Compound",
    instructions: "Hinge at the hips with a flat back, pull the bar toward your lower ribcage, squeezing shoulder blades together, then lower with control.",
    commonMistakes: "Standing too upright, using momentum to jerk the weight up.",
    tips: "Keep your torso angle consistent throughout every rep.",
  },
  {
    name: "Pendlay Row",
    muscleGroup: "Back",
    secondaryMuscles: ["Biceps", "Forearms"],
    equipment: "Barbell",
    difficulty: "Advanced",
    exerciseType: "Compound",
    instructions: "Starting with the bar on the floor each rep, hinge with a flat back parallel to the ground, and explosively row the bar to your torso.",
    commonMistakes: "Using leg drive to heave the bar up instead of the back.",
    tips: "Reset fully on the floor each rep to eliminate momentum.",
  },
  {
    name: "T-Bar Row",
    muscleGroup: "Back",
    secondaryMuscles: ["Biceps", "Forearms"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    exerciseType: "Compound",
    instructions: "Straddle the bar, hinge forward with a flat back, and row the handle up toward your chest, squeezing your back at the top.",
    commonMistakes: "Jerking the weight with the lower back instead of rowing with the lats.",
    tips: "Keep your chest up and core braced throughout the set.",
  },
  {
    name: "Seated Cable Row",
    muscleGroup: "Back",
    secondaryMuscles: ["Biceps", "Forearms"],
    equipment: "Cable",
    difficulty: "Beginner",
    exerciseType: "Compound",
    instructions: "Sit with knees slightly bent, pull the handle toward your torso while keeping your back straight, then extend arms fully with control.",
    commonMistakes: "Rounding the back at full stretch, leaning too far back to move more weight.",
    tips: "Pause and squeeze your shoulder blades together at the end of each rep.",
  },
  {
    name: "One-Arm Dumbbell Row",
    muscleGroup: "Back",
    secondaryMuscles: ["Biceps", "Forearms"],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    exerciseType: "Compound",
    instructions: "Support yourself with one hand and knee on a bench, row the dumbbell up toward your hip, then lower with control.",
    commonMistakes: "Rotating the torso to help lift the weight, using a too-heavy dumbbell.",
    tips: "Keep your torso parallel to the floor and pull with your elbow, not your hand.",
  },
  {
    name: "Chest-Supported Row",
    muscleGroup: "Back",
    secondaryMuscles: ["Biceps"],
    equipment: "Machine",
    difficulty: "Beginner",
    exerciseType: "Compound",
    instructions: "Lie chest-down on the pad, row the handles toward your torso, squeezing your shoulder blades, then extend with control.",
    commonMistakes: "Lifting the chest off the pad to add momentum.",
    tips: "The chest support removes lower-back strain, letting you focus purely on the back.",
  },
  {
    name: "Inverted Row",
    muscleGroup: "Back",
    secondaryMuscles: ["Biceps", "Core"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    exerciseType: "Compound",
    instructions: "Lie under a fixed bar, body straight, pull your chest up to the bar, then lower with control.",
    commonMistakes: "Sagging the hips, not achieving full range of motion.",
    tips: "Adjust bar height or foot position to scale difficulty up or down.",
  },
  {
    name: "Good Morning",
    muscleGroup: "Back",
    secondaryMuscles: ["Legs", "Glutes"],
    equipment: "Barbell",
    difficulty: "Advanced",
    exerciseType: "Compound",
    instructions: "With the bar on your upper back, hinge forward at the hips keeping a flat back, then return to standing by driving your hips forward.",
    commonMistakes: "Rounding the back, using too much weight too soon.",
    tips: "Start light — this movement rewards perfect form over ego lifting.",
  },

  // ============================================================
  // SHOULDERS
  // ============================================================
  {
    name: "Barbell Overhead Press",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Triceps", "Core"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    exerciseType: "Compound",
    instructions: "Stand with the bar at shoulder height, press it overhead to full lockout while keeping your core tight, then lower back to shoulders.",
    commonMistakes: "Overarching the lower back, pressing the bar forward instead of straight up.",
    tips: "Squeeze your glutes to keep your torso stacked and stable.",
  },
  {
    name: "Seated Dumbbell Shoulder Press",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Triceps"],
    equipment: "Dumbbell",
    difficulty: "Intermediate",
    exerciseType: "Compound",
    instructions: "Sit with back supported, press dumbbells from shoulder height to full overhead extension, then lower with control.",
    commonMistakes: "Arching the back excessively, letting the dumbbells drift forward.",
    tips: "Keep your wrists stacked directly over your elbows throughout the press.",
  },
  {
    name: "Arnold Press",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Triceps"],
    equipment: "Dumbbell",
    difficulty: "Intermediate",
    exerciseType: "Compound",
    instructions: "Start with dumbbells in front of your shoulders, palms facing you. Rotate and press overhead as arms extend, then reverse on the way down.",
    commonMistakes: "Rushing the rotation, losing core stability during the press.",
    tips: "Move slowly through the rotation to maximize shoulder engagement.",
  },
  {
    name: "Machine Shoulder Press",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Triceps"],
    equipment: "Machine",
    difficulty: "Beginner",
    exerciseType: "Compound",
    instructions: "Sit with back against the pad, press the handles overhead to full extension, then lower under control.",
    commonMistakes: "Setting the seat too low or high, misaligning the shoulder joint with the handles.",
    tips: "Good option for building pressing strength without needing shoulder stabilization.",
  },
  {
    name: "Push Press",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Legs", "Triceps"],
    equipment: "Barbell",
    difficulty: "Advanced",
    exerciseType: "Compound",
    instructions: "Dip slightly at the knees, then explosively drive up and press the bar overhead using the leg drive to help lockout.",
    commonMistakes: "Dipping too deep, losing the vertical bar path.",
    tips: "Use a short, sharp dip — this isn't a squat, just enough to generate upward momentum.",
  },
  {
    name: "Dumbbell Lateral Raise",
    muscleGroup: "Shoulders",
    secondaryMuscles: [],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Stand holding dumbbells at your sides, raise them out to shoulder height with a slight bend in the elbows, then lower slowly.",
    commonMistakes: "Using momentum to swing the weights, raising above shoulder height.",
    tips: "Lead with your elbows, not your hands, and control the descent.",
  },
  {
    name: "Cable Lateral Raise",
    muscleGroup: "Shoulders",
    secondaryMuscles: [],
    equipment: "Cable",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Stand side-on to a low cable pulley, raise the handle out to shoulder height, then lower under constant tension.",
    commonMistakes: "Leaning away from the cable to cheat the weight up.",
    tips: "Cables keep tension on the delt even at the bottom of the movement, unlike dumbbells.",
  },
  {
    name: "Front Raise",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Core"],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Hold dumbbells in front of your thighs, raise them straight out in front to shoulder height, then lower with control.",
    commonMistakes: "Swinging the weight using the lower back, raising too high above shoulder level.",
    tips: "Alternate arms or raise both together — either way, keep the movement slow.",
  },
  {
    name: "Rear Delt Fly",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Back"],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Hinge forward at the hips with dumbbells hanging down, raise arms out to the sides squeezing shoulder blades, then lower slowly.",
    commonMistakes: "Using momentum or too heavy a weight, causing the back to round.",
    tips: "Keep a slight bend in the elbows and focus on the squeeze at the top.",
  },
  {
    name: "Cable Rear Delt Fly",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Back"],
    equipment: "Cable",
    difficulty: "Intermediate",
    exerciseType: "Isolation",
    instructions: "Cross the cables in front of you, pull the handles out and back in a wide arc, squeezing your rear delts, then return slowly.",
    commonMistakes: "Turning it into a row by bending the elbows too much.",
    tips: "Keep your arms relatively straight to keep the tension on the rear delts.",
  },
  {
    name: "Face Pull",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Back"],
    equipment: "Cable",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Set a cable at face height with a rope attachment, pull it toward your face while flaring elbows out, squeezing the rear delts.",
    commonMistakes: "Using too much weight and turning it into a row.",
    tips: "Focus on external rotation at the end of the movement for rear delt health.",
  },
  {
    name: "Upright Row",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Back"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    exerciseType: "Compound",
    instructions: "Hold the bar with a narrow overhand grip, pull it straight up along your body to chest height, leading with your elbows.",
    commonMistakes: "Pulling the bar too high, which can strain the shoulder joint.",
    tips: "Stop the pull once elbows reach shoulder height.",
  },
  {
    name: "Barbell Shrug",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Back"],
    equipment: "Barbell",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Hold the bar at arm's length in front of you, elevate your shoulders straight up toward your ears, then lower with control.",
    commonMistakes: "Rolling the shoulders instead of a straight up-and-down motion.",
    tips: "Pause briefly at the top for a stronger trap contraction.",
  },
  {
    name: "Band Pull-Apart",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Back"],
    equipment: "Resistance Band",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Hold a resistance band at shoulder height with arms extended, pull it apart by squeezing your shoulder blades together, then return slowly.",
    commonMistakes: "Bending the elbows to cheat the band apart.",
    tips: "Great warm-up or high-rep finisher for shoulder and upper-back health.",
  },

  // ============================================================
  // BICEPS
  // ============================================================
  {
    name: "Barbell Curl",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Forearms"],
    equipment: "Barbell",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Stand holding the bar with an underhand grip, curl it up toward your shoulders while keeping elbows fixed at your sides, then lower slowly.",
    commonMistakes: "Swinging the torso to generate momentum, flaring elbows outward.",
    tips: "Keep elbows pinned to your sides for full bicep isolation.",
  },
  {
    name: "EZ Bar Curl",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Forearms"],
    equipment: "EZ Bar",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Using the angled grips of the EZ bar, curl the weight up toward your shoulders, then lower with control.",
    commonMistakes: "Using a grip width that feels awkward on the wrists.",
    tips: "The angled bar is easier on the wrists than a straight barbell.",
  },
  {
    name: "Dumbbell Curl",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Forearms"],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Stand holding dumbbells at your sides with palms facing forward, curl them up toward your shoulders, then lower slowly.",
    commonMistakes: "Swinging the elbows forward, using momentum from the shoulders.",
    tips: "Curl one arm at a time or alternate for better focus on form.",
  },
  {
    name: "Dumbbell Hammer Curl",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Forearms"],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Hold dumbbells with a neutral grip, curl them up toward your shoulders while keeping palms facing each other, then lower with control.",
    commonMistakes: "Using momentum, letting elbows drift forward.",
    tips: "This variation emphasizes the brachialis and forearms alongside the biceps.",
  },
  {
    name: "Cable Curl",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Forearms"],
    equipment: "Cable",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Stand facing the cable machine, curl the bar attachment up toward your shoulders, then lower with control against the constant tension.",
    commonMistakes: "Leaning back to use momentum, rushing the eccentric.",
    tips: "Cables keep constant tension throughout, so slow reps are especially effective.",
  },
  {
    name: "Preacher Curl",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Forearms"],
    equipment: "EZ Bar",
    difficulty: "Intermediate",
    exerciseType: "Isolation",
    instructions: "Rest your upper arms on the preacher pad, curl the bar up toward your shoulders, then lower until arms are nearly fully extended.",
    commonMistakes: "Not controlling the bottom stretch, lifting elbows off the pad.",
    tips: "Avoid locking out fully at the bottom to keep tension on the biceps.",
  },
  {
    name: "Concentration Curl",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Forearms"],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Sit on a bench, brace your elbow against your inner thigh, and curl the dumbbell up while keeping your upper arm still.",
    commonMistakes: "Letting the elbow drift away from the thigh, using body momentum.",
    tips: "Squeeze hard at the top of each rep for peak contraction.",
  },
  {
    name: "Incline Dumbbell Curl",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Forearms"],
    equipment: "Dumbbell",
    difficulty: "Intermediate",
    exerciseType: "Isolation",
    instructions: "Sit on an incline bench with arms hanging straight down, curl the dumbbells up toward your shoulders, then lower to a full stretch.",
    commonMistakes: "Letting the elbows drift forward as the weight gets heavy.",
    tips: "The incline position increases the stretch on the long head of the biceps.",
  },
  {
    name: "Cable Rope Hammer Curl",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Forearms"],
    equipment: "Cable",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Using a rope attachment on a low cable, curl it up toward your shoulders keeping palms facing each other throughout.",
    commonMistakes: "Letting elbows flare out to the sides.",
    tips: "Squeeze the rope ends apart slightly at the top for extra brachialis activation.",
  },
  {
    name: "Spider Curl",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Forearms"],
    equipment: "EZ Bar",
    difficulty: "Intermediate",
    exerciseType: "Isolation",
    instructions: "Lie face-down on an incline bench with arms hanging, curl the bar up toward your face, then lower to a full stretch.",
    commonMistakes: "Not achieving a full range of motion, letting elbows move backward.",
    tips: "This position removes all momentum, making it a brutally effective isolation move.",
  },
  {
    name: "Band Bicep Curl",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Forearms"],
    equipment: "Resistance Band",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Stand on the band with feet shoulder-width apart, curl the handles up toward your shoulders, then lower with control.",
    commonMistakes: "Standing on the band unevenly, causing uneven resistance between arms.",
    tips: "Bands provide increasing resistance the higher you curl — control the top portion especially.",
  },

  // ============================================================
  // TRICEPS
  // ============================================================
  {
    name: "Rope Tricep Pushdown",
    muscleGroup: "Triceps",
    secondaryMuscles: [],
    equipment: "Cable",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Stand facing the cable machine, elbows pinned to your sides, push the rope down and apart until arms are fully extended, then control it back up.",
    commonMistakes: "Letting elbows flare out or drift forward, using body weight to push the bar down.",
    tips: "Spread the rope ends apart at the bottom for a stronger triceps squeeze.",
  },
  {
    name: "Straight Bar Tricep Pushdown",
    muscleGroup: "Triceps",
    secondaryMuscles: [],
    equipment: "Cable",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Using a straight bar attachment, push down until your arms are fully extended, keeping elbows locked at your sides throughout.",
    commonMistakes: "Using a wide grip that shifts stress off the triceps.",
    tips: "Keep wrists neutral and avoid bending them during the push.",
  },
  {
    name: "Skull Crushers",
    muscleGroup: "Triceps",
    secondaryMuscles: [],
    equipment: "EZ Bar",
    difficulty: "Intermediate",
    exerciseType: "Isolation",
    instructions: "Lie on a bench holding the bar above your chest, lower it toward your forehead by bending only at the elbows, then extend back up.",
    commonMistakes: "Letting elbows flare outward, moving the upper arm instead of just the forearm.",
    tips: "Keep upper arms perpendicular to the floor throughout the movement.",
  },
  {
    name: "Overhead Dumbbell Tricep Extension",
    muscleGroup: "Triceps",
    secondaryMuscles: [],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Hold a dumbbell overhead with both hands, lower it behind your head by bending the elbows, then extend back to full lockout.",
    commonMistakes: "Flaring elbows out wide, arching the lower back.",
    tips: "Keep your elbows close to your head throughout the movement.",
  },
  {
    name: "Overhead Cable Tricep Extension",
    muscleGroup: "Triceps",
    secondaryMuscles: [],
    equipment: "Cable",
    difficulty: "Intermediate",
    exerciseType: "Isolation",
    instructions: "Facing away from a low cable, extend the rope overhead until arms are straight, then return under control.",
    commonMistakes: "Leaning too far forward, letting elbows drift outward.",
    tips: "The cable keeps tension on the long head of the triceps throughout the full range.",
  },
  {
    name: "Close-Grip Bench Press",
    muscleGroup: "Triceps",
    secondaryMuscles: ["Chest", "Shoulders"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    exerciseType: "Compound",
    instructions: "Grip the bar just inside shoulder-width, lower it to your lower chest keeping elbows tucked, then press back up to full extension.",
    commonMistakes: "Gripping too narrow and straining the wrists, flaring elbows wide.",
    tips: "Keep elbows tucked at roughly a 30-45 degree angle from your torso.",
  },
  {
    name: "Bench Dips",
    muscleGroup: "Triceps",
    secondaryMuscles: ["Shoulders", "Chest"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    exerciseType: "Compound",
    instructions: "Place your hands on a bench behind you, legs extended in front, lower your body by bending elbows, then press back up.",
    commonMistakes: "Lowering too deep and straining the shoulders, letting hips drift away from the bench.",
    tips: "Keep hips close to the bench throughout to protect the shoulder joint.",
  },
  {
    name: "Diamond Push-Up",
    muscleGroup: "Triceps",
    secondaryMuscles: ["Chest", "Core"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    exerciseType: "Compound",
    instructions: "Form a diamond shape with your hands under your chest, lower your body keeping elbows close, then push back up.",
    commonMistakes: "Flaring elbows out wide, sagging the hips.",
    tips: "Keep your core tight to maintain a straight line from head to heels.",
  },
  {
    name: "Dumbbell Tricep Kickback",
    muscleGroup: "Triceps",
    secondaryMuscles: [],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Hinge forward with your upper arm parallel to the floor, extend your forearm back until the arm is straight, then return with control.",
    commonMistakes: "Swinging the weight using the shoulder instead of just extending the elbow.",
    tips: "Keep the upper arm still and stationary — only the forearm should move.",
  },
  {
    name: "Machine Tricep Extension",
    muscleGroup: "Triceps",
    secondaryMuscles: [],
    equipment: "Machine",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Sit with upper arms resting on the pad, extend your forearms down against the resistance, then return with control.",
    commonMistakes: "Using momentum, adjusting the seat incorrectly so the elbow joint isn't aligned with the pivot.",
    tips: "A stable option for isolating the triceps without needing balance or bracing.",
  },

  // ============================================================
  // LEGS
  // ============================================================
  {
    name: "Barbell Back Squat",
    muscleGroup: "Legs",
    secondaryMuscles: ["Glutes", "Core"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    exerciseType: "Compound",
    instructions: "Rest the bar on your upper back, feet shoulder-width apart. Squat down until thighs are parallel to the floor, then drive back up.",
    commonMistakes: "Knees caving inward, heels lifting off the floor, insufficient depth.",
    tips: "Brace your core hard before descending and keep your chest up.",
  },
  {
    name: "Front Squat",
    muscleGroup: "Legs",
    secondaryMuscles: ["Glutes", "Core"],
    equipment: "Barbell",
    difficulty: "Advanced",
    exerciseType: "Compound",
    instructions: "Rest the bar across the front of your shoulders, elbows high, squat down keeping your torso upright, then drive back up.",
    commonMistakes: "Letting elbows drop, which causes the bar to roll forward.",
    tips: "This variation demands a more upright torso, emphasizing the quads.",
  },
  {
    name: "Hack Squat",
    muscleGroup: "Legs",
    secondaryMuscles: ["Glutes"],
    equipment: "Machine",
    difficulty: "Intermediate",
    exerciseType: "Compound",
    instructions: "Position your shoulders under the pads, feet shoulder-width on the platform, lower into a squat, then press back up.",
    commonMistakes: "Placing feet too high or low, which shifts stress off the quads.",
    tips: "A more forward foot position emphasizes the glutes and hamstrings more.",
  },
  {
    name: "Leg Press",
    muscleGroup: "Legs",
    secondaryMuscles: ["Glutes"],
    equipment: "Machine",
    difficulty: "Beginner",
    exerciseType: "Compound",
    instructions: "Sit in the machine with feet shoulder-width on the platform, lower the weight until knees reach about 90 degrees, then press back up.",
    commonMistakes: "Locking knees aggressively at the top, letting knees cave in.",
    tips: "Don't let your lower back round off the pad at the bottom.",
  },
  {
    name: "Goblet Squat",
    muscleGroup: "Legs",
    secondaryMuscles: ["Glutes", "Core"],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    exerciseType: "Compound",
    instructions: "Hold a dumbbell vertically against your chest, squat down between your knees, then drive back up to standing.",
    commonMistakes: "Letting the chest drop forward, not reaching sufficient depth.",
    tips: "A great teaching tool for learning proper squat depth and bracing.",
  },
  {
    name: "Walking Lunge",
    muscleGroup: "Legs",
    secondaryMuscles: ["Glutes", "Core"],
    equipment: "Dumbbell",
    difficulty: "Intermediate",
    exerciseType: "Compound",
    instructions: "Step forward into a lunge, lowering your back knee toward the floor, then push through the front heel to step into the next lunge.",
    commonMistakes: "Taking too short a step, letting the front knee travel past the toes excessively.",
    tips: "Keep your torso upright and core engaged for balance.",
  },
  {
    name: "Bulgarian Split Squat",
    muscleGroup: "Legs",
    secondaryMuscles: ["Glutes", "Core"],
    equipment: "Dumbbell",
    difficulty: "Advanced",
    exerciseType: "Compound",
    instructions: "Rest your rear foot on a bench behind you, lower your body until your front thigh is parallel to the floor, then drive back up.",
    commonMistakes: "Letting the front knee cave inward, placing the rear foot too close to the front leg.",
    tips: "Keep most of your weight through the front heel for balance and quad/glute engagement.",
  },
  {
    name: "Step-Up",
    muscleGroup: "Legs",
    secondaryMuscles: ["Glutes"],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    exerciseType: "Compound",
    instructions: "Holding dumbbells at your sides, step up onto a box or bench with one leg, driving through the heel, then step back down.",
    commonMistakes: "Pushing off the trailing leg instead of driving through the lead leg.",
    tips: "Use a box height where your knee is at roughly 90 degrees at the bottom of the step.",
  },
  {
    name: "Leg Extension",
    muscleGroup: "Legs",
    secondaryMuscles: [],
    equipment: "Machine",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Sit in the machine with pad resting on your shins, extend your legs fully, then lower with control.",
    commonMistakes: "Using momentum, not controlling the eccentric portion.",
    tips: "Pause briefly at full extension to maximize quad contraction.",
  },
  {
    name: "Lying Leg Curl",
    muscleGroup: "Legs",
    secondaryMuscles: ["Glutes"],
    equipment: "Machine",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Lie face down with the pad against your ankles, curl your heels toward your glutes, then lower slowly.",
    commonMistakes: "Lifting hips off the bench, using momentum instead of a controlled squeeze.",
    tips: "Keep hips pressed into the pad throughout the movement.",
  },
  {
    name: "Seated Leg Curl",
    muscleGroup: "Legs",
    secondaryMuscles: ["Glutes"],
    equipment: "Machine",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Sit with the pad against your lower shins, curl your legs down and back, then return to the start with control.",
    commonMistakes: "Not adjusting the machine to fit your leg length, causing an awkward pivot point.",
    tips: "This position stretches the hamstrings well at the top of the range.",
  },
  {
    name: "Romanian Deadlift",
    muscleGroup: "Legs",
    secondaryMuscles: ["Glutes", "Back"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    exerciseType: "Compound",
    instructions: "Hold the bar at hip level, hinge at the hips while keeping legs mostly straight, lowering the bar along your shins, then drive hips forward to return.",
    commonMistakes: "Rounding the back, bending the knees too much and turning it into a squat.",
    tips: "Push your hips back as far as possible before your back starts to round.",
  },
  {
    name: "Dumbbell Stiff-Leg Deadlift",
    muscleGroup: "Legs",
    secondaryMuscles: ["Glutes", "Back"],
    equipment: "Dumbbell",
    difficulty: "Intermediate",
    exerciseType: "Compound",
    instructions: "Holding dumbbells in front of your thighs, hinge at the hips with minimal knee bend, lower until you feel a hamstring stretch, then return to standing.",
    commonMistakes: "Rounding the lower back, bending the knees excessively.",
    tips: "Keep the dumbbells close to your legs throughout the movement.",
  },
  {
    name: "Standing Calf Raise",
    muscleGroup: "Legs",
    secondaryMuscles: [],
    equipment: "Machine",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Stand on the platform with balls of your feet, lower your heels below the platform, then rise up onto your toes as high as possible.",
    commonMistakes: "Using a partial range of motion, bouncing at the bottom.",
    tips: "Pause at the top for a full second to maximize calf contraction.",
  },
  {
    name: "Seated Calf Raise",
    muscleGroup: "Legs",
    secondaryMuscles: [],
    equipment: "Machine",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Sit with the pad resting on your knees, lower your heels, then raise up onto your toes as high as possible.",
    commonMistakes: "Rushing through reps instead of pausing at full stretch and contraction.",
    tips: "The seated position targets the soleus more than the standing variation.",
  },
  {
    name: "Smith Machine Squat",
    muscleGroup: "Legs",
    secondaryMuscles: ["Glutes"],
    equipment: "Smith Machine",
    difficulty: "Beginner",
    exerciseType: "Compound",
    instructions: "Position the bar on your upper back within the fixed track, squat down until thighs are parallel, then press back up.",
    commonMistakes: "Placing feet too close under the bar, which restricts natural squat mechanics.",
    tips: "Step your feet slightly forward from the bar to allow a more natural squat path.",
  },
  {
    name: "Band Squat",
    muscleGroup: "Legs",
    secondaryMuscles: ["Glutes"],
    equipment: "Resistance Band",
    difficulty: "Beginner",
    exerciseType: "Compound",
    instructions: "Stand on a resistance band with it looped over your shoulders, squat down and drive back up against the band's resistance.",
    commonMistakes: "Letting the band slip off-center, causing uneven resistance.",
    tips: "Great for bodyweight-squat progression when you don't have access to a barbell.",
  },

  // ============================================================
  // CORE
  // ============================================================
  {
    name: "Plank",
    muscleGroup: "Core",
    secondaryMuscles: ["Shoulders"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Support your body on forearms and toes, keeping a straight line from head to heels, and hold the position.",
    commonMistakes: "Sagging hips, raising hips too high, holding your breath.",
    tips: "Squeeze your glutes and brace your core like you're about to be punched in the stomach.",
  },
  {
    name: "Side Plank",
    muscleGroup: "Core",
    secondaryMuscles: ["Shoulders"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    exerciseType: "Isolation",
    instructions: "Lie on your side, prop yourself up on one forearm, lift your hips so your body forms a straight line, and hold.",
    commonMistakes: "Letting the hips sag toward the floor, rotating the torso forward or back.",
    tips: "Stack your feet and keep your hips high throughout the hold.",
  },
  {
    name: "Hanging Leg Raise",
    muscleGroup: "Core",
    secondaryMuscles: ["Forearms"],
    equipment: "Bodyweight",
    difficulty: "Advanced",
    exerciseType: "Isolation",
    instructions: "Hang from a pull-up bar, raise your legs up to hip height or higher by curling the pelvis, then lower with control.",
    commonMistakes: "Swinging the body for momentum, not controlling the descent.",
    tips: "Focus on curling your pelvis rather than just lifting the legs from the hips.",
  },
  {
    name: "Cable Crunch",
    muscleGroup: "Core",
    secondaryMuscles: [],
    equipment: "Cable",
    difficulty: "Intermediate",
    exerciseType: "Isolation",
    instructions: "Kneel below a cable pulley holding the rope by your head, crunch down by flexing your spine, then return to the start under control.",
    commonMistakes: "Pulling with the arms instead of flexing through the abs, using the hips to move the weight.",
    tips: "Keep your hips fixed and focus purely on spinal flexion.",
  },
  {
    name: "Russian Twist",
    muscleGroup: "Core",
    secondaryMuscles: [],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Sit with knees bent and torso leaned back slightly, rotate your torso side to side, optionally holding a weight.",
    commonMistakes: "Moving only the arms instead of rotating the torso, rounding the lower back.",
    tips: "Keep your chest up and move slowly to maximize the rotational contraction.",
  },
  {
    name: "Ab Wheel Rollout",
    muscleGroup: "Core",
    secondaryMuscles: ["Shoulders", "Back"],
    equipment: "Other",
    difficulty: "Advanced",
    exerciseType: "Compound",
    instructions: "Kneel holding the ab wheel, roll it forward as far as you can while keeping your core braced, then pull back to the start.",
    commonMistakes: "Letting the lower back sag, rolling out too far too soon.",
    tips: "Start with a small range of motion and progress gradually as core strength improves.",
  },
  {
    name: "Bicycle Crunch",
    muscleGroup: "Core",
    secondaryMuscles: [],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Lie on your back, hands behind your head, bring opposite elbow to opposite knee in a pedaling motion.",
    commonMistakes: "Pulling on the neck with the hands, moving too quickly with poor control.",
    tips: "Focus on the rotation coming from your abs, not your arms yanking your head up.",
  },
  {
    name: "Sit-Up",
    muscleGroup: "Core",
    secondaryMuscles: [],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Lie on your back with knees bent, feet anchored, curl your torso up until you're sitting upright, then lower with control.",
    commonMistakes: "Using momentum by yanking the torso up, pulling on the neck.",
    tips: "Cross your arms over your chest to reduce the temptation to use momentum.",
  },
  {
    name: "Mountain Climbers",
    muscleGroup: "Core",
    secondaryMuscles: ["Legs"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    exerciseType: "Compound",
    instructions: "Start in a plank position, drive your knees alternately toward your chest at a quick pace while keeping your hips level.",
    commonMistakes: "Letting hips rise too high, losing plank alignment as fatigue sets in.",
    tips: "Keep your core braced throughout to avoid your lower back sagging.",
  },
  {
    name: "Cable Woodchopper",
    muscleGroup: "Core",
    secondaryMuscles: ["Shoulders"],
    equipment: "Cable",
    difficulty: "Intermediate",
    exerciseType: "Isolation",
    instructions: "Set the cable high, pull it diagonally across your body down to the opposite hip, rotating through your torso, then return with control.",
    commonMistakes: "Using the arms to pull instead of rotating through the core.",
    tips: "Keep your hips relatively stable and let the rotation come from your obliques.",
  },

  // ============================================================
  // FOREARMS
  // ============================================================
  {
    name: "Wrist Curl",
    muscleGroup: "Forearms",
    secondaryMuscles: [],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Rest forearms on a bench with wrists hanging off the edge, palms up, curl the weight up using only your wrists, then lower slowly.",
    commonMistakes: "Using the whole forearm to swing the weight instead of isolating the wrist.",
    tips: "Use a light weight and focus on a full range of motion.",
  },
  {
    name: "Reverse Wrist Curl",
    muscleGroup: "Forearms",
    secondaryMuscles: [],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Rest forearms on a bench with palms facing down, extend your wrists upward against the weight, then lower with control.",
    commonMistakes: "Using too much weight, which limits range of motion.",
    tips: "This builds the extensor muscles that balance out heavy grip and curl work.",
  },
  {
    name: "Barbell Reverse Curl",
    muscleGroup: "Forearms",
    secondaryMuscles: ["Biceps"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    exerciseType: "Isolation",
    instructions: "Hold the bar with an overhand grip, curl it up toward your shoulders keeping elbows fixed at your sides, then lower with control.",
    commonMistakes: "Using a grip that's too wide, swinging the torso for momentum.",
    tips: "This grip heavily emphasizes the brachioradialis and forearm extensors.",
  },
  {
    name: "Farmer's Carry",
    muscleGroup: "Forearms",
    secondaryMuscles: ["Core", "Back"],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    exerciseType: "Compound",
    instructions: "Pick up a heavy dumbbell or kettlebell in each hand and walk for a set distance or time while keeping your posture tall.",
    commonMistakes: "Letting shoulders round forward, shortening your stride excessively.",
    tips: "Keep your core braced and shoulders back as if standing at attention.",
  },
  {
    name: "Plate Pinch Hold",
    muscleGroup: "Forearms",
    secondaryMuscles: [],
    equipment: "Other",
    difficulty: "Intermediate",
    exerciseType: "Isolation",
    instructions: "Pinch two weight plates together with your fingers and thumb, and hold for time without letting them slip.",
    commonMistakes: "Using plates that are too heavy too soon, leading to poor grip mechanics.",
    tips: "Build up hold time gradually — this move punishes ego lifting quickly.",
  },
  {
    name: "Wrist Roller",
    muscleGroup: "Forearms",
    secondaryMuscles: [],
    equipment: "Other",
    difficulty: "Intermediate",
    exerciseType: "Isolation",
    instructions: "Hold the roller with arms extended in front of you, roll the weight up by twisting the wrists alternately, then reverse to lower it.",
    commonMistakes: "Using the shoulders to help instead of isolating the wrist rotation.",
    tips: "Keep arms extended and stationary — all the work should come from wrist rotation.",
  },

  // ============================================================
  // GLUTES
  // ============================================================
  {
    name: "Barbell Hip Thrust",
    muscleGroup: "Glutes",
    secondaryMuscles: ["Legs"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    exerciseType: "Compound",
    instructions: "Sit with your upper back against a bench and the bar over your hips, drive through your heels to lift your hips until your body forms a straight line, then lower.",
    commonMistakes: "Overextending the lower back at the top, not reaching full hip extension.",
    tips: "Tuck your chin slightly and squeeze your glutes hard at the top of every rep.",
  },
  {
    name: "Glute Bridge",
    muscleGroup: "Glutes",
    secondaryMuscles: ["Legs", "Core"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Lie on your back with knees bent, feet flat on the floor, drive your hips up by squeezing your glutes, then lower with control.",
    commonMistakes: "Pushing through the toes instead of the heels, arching the lower back excessively.",
    tips: "Drive through your heels and pause at the top for a strong glute squeeze.",
  },
  {
    name: "Cable Glute Kickback",
    muscleGroup: "Glutes",
    secondaryMuscles: ["Legs"],
    equipment: "Cable",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Attach an ankle strap to a low cable, kick your leg back and up while keeping your core braced, then return with control.",
    commonMistakes: "Using the lower back to generate momentum instead of the glute.",
    tips: "Keep the movement slow and controlled, focusing on squeezing the glute at the top.",
  },
  {
    name: "Cable Pull Through",
    muscleGroup: "Glutes",
    secondaryMuscles: ["Legs", "Back"],
    equipment: "Cable",
    difficulty: "Intermediate",
    exerciseType: "Compound",
    instructions: "Facing away from a low cable with the rope between your legs, hinge at the hips, then drive forward by squeezing your glutes to standing.",
    commonMistakes: "Squatting instead of hinging, rounding the lower back.",
    tips: "This teaches a strong hip hinge pattern without loading the spine directly.",
  },
  {
    name: "Sumo Squat",
    muscleGroup: "Glutes",
    secondaryMuscles: ["Legs"],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    exerciseType: "Compound",
    instructions: "Stand with a wide stance and toes pointed out, hold a dumbbell with both hands, squat down between your legs, then drive back up.",
    commonMistakes: "Letting knees cave in, not reaching sufficient depth.",
    tips: "The wide stance biases the glutes and inner thighs more than a standard squat.",
  },
  {
    name: "Single-Leg Glute Bridge",
    muscleGroup: "Glutes",
    secondaryMuscles: ["Legs", "Core"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    exerciseType: "Isolation",
    instructions: "Lie on your back with one foot planted and the other leg extended, drive your hips up through the planted heel, then lower with control.",
    commonMistakes: "Letting the hips rotate or tilt to one side.",
    tips: "Keep your hips square to the ceiling throughout the movement.",
  },
  {
    name: "Donkey Kick",
    muscleGroup: "Glutes",
    secondaryMuscles: ["Core"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "On all fours, kick one leg back and up while keeping the knee bent at 90 degrees, then lower with control.",
    commonMistakes: "Arching the lower back to gain extra height, using momentum.",
    tips: "Focus on squeezing the glute at the top rather than how high you can kick.",
  },
  {
    name: "Machine Hip Abduction",
    muscleGroup: "Glutes",
    secondaryMuscles: [],
    equipment: "Machine",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Sit in the machine with pads against your outer thighs, push your legs apart against the resistance, then return with control.",
    commonMistakes: "Using momentum to swing the legs open, leaning the torso excessively.",
    tips: "Targets the gluteus medius, which helps with hip stability.",
  },
  {
    name: "Frog Pump",
    muscleGroup: "Glutes",
    secondaryMuscles: [],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    exerciseType: "Isolation",
    instructions: "Lie on your back with the soles of your feet together and knees splayed out, drive your hips up by squeezing your glutes, then lower with control.",
    commonMistakes: "Using a very short range of motion, not achieving a full squeeze at the top.",
    tips: "Great high-rep finisher at the end of a lower body session.",
  },

  // ============================================================
  // FULL BODY
  // ============================================================
  {
    name: "Kettlebell Swing",
    muscleGroup: "Full Body",
    secondaryMuscles: ["Glutes", "Back", "Core"],
    equipment: "Kettlebell",
    difficulty: "Intermediate",
    exerciseType: "Compound",
    instructions: "Hinge at the hips to swing the kettlebell between your legs, then explosively drive your hips forward to swing it to chest height.",
    commonMistakes: "Squatting instead of hinging, using the arms to lift the weight.",
    tips: "The power should come from an explosive hip snap, not the shoulders.",
  },
  {
    name: "Burpee",
    muscleGroup: "Full Body",
    secondaryMuscles: ["Chest", "Legs", "Core"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    exerciseType: "Compound",
    instructions: "Drop into a squat, kick your feet back into a plank, perform a push-up, jump feet back in, then explode upward into a jump.",
    commonMistakes: "Sagging hips during the plank/push-up phase, skipping the full jump.",
    tips: "Move at a controlled pace first to nail the form before adding speed.",
  },
  {
    name: "Dumbbell Thruster",
    muscleGroup: "Full Body",
    secondaryMuscles: ["Legs", "Shoulders", "Core"],
    equipment: "Dumbbell",
    difficulty: "Advanced",
    exerciseType: "Compound",
    instructions: "Hold dumbbells at shoulder height, squat down, then explosively stand and press the weights overhead in one fluid motion.",
    commonMistakes: "Pausing between the squat and the press, losing core tightness during the press.",
    tips: "Use the momentum from standing up to help drive the press overhead.",
  },
  {
    name: "Barbell Clean and Press",
    muscleGroup: "Full Body",
    secondaryMuscles: ["Back", "Shoulders", "Legs"],
    equipment: "Barbell",
    difficulty: "Advanced",
    exerciseType: "Compound",
    instructions: "Explosively pull the bar from the floor to shoulder height in one motion, then press it overhead to full lockout.",
    commonMistakes: "Rounding the back during the pull, muscling the bar up with the arms instead of the legs and hips.",
    tips: "This is a technical lift — start light and prioritize form over load.",
  },
  {
    name: "Renegade Row",
    muscleGroup: "Full Body",
    secondaryMuscles: ["Back", "Core", "Shoulders"],
    equipment: "Dumbbell",
    difficulty: "Advanced",
    exerciseType: "Compound",
    instructions: "In a plank position with hands on dumbbells, row one dumbbell up to your hip while balancing on the other, then alternate.",
    commonMistakes: "Rotating the hips excessively, losing plank position.",
    tips: "Widen your stance for more stability while learning the movement.",
  },
  {
    name: "Man Maker",
    muscleGroup: "Full Body",
    secondaryMuscles: ["Back", "Shoulders", "Legs", "Core"],
    equipment: "Dumbbell",
    difficulty: "Advanced",
    exerciseType: "Compound",
    instructions: "From a plank with hands on dumbbells, perform a push-up, row each arm, jump feet in, then stand and press the dumbbells overhead.",
    commonMistakes: "Rushing through the transitions and losing form on any single component.",
    tips: "Master each component movement separately before chaining them together.",
  },
  {
    name: "Turkish Get-Up",
    muscleGroup: "Full Body",
    secondaryMuscles: ["Core", "Shoulders", "Legs"],
    equipment: "Kettlebell",
    difficulty: "Advanced",
    exerciseType: "Compound",
    instructions: "Starting lying down with a kettlebell pressed overhead, work through a series of steps to stand up fully while keeping the weight locked out overhead, then reverse the sequence to return to the floor.",
    commonMistakes: "Losing the overhead lockout, rushing through the sequence.",
    tips: "Practice the movement with no weight first to learn the sequence.",
  },
  {
    name: "Wall Ball Shot",
    muscleGroup: "Full Body",
    secondaryMuscles: ["Legs", "Shoulders", "Core"],
    equipment: "Other",
    difficulty: "Intermediate",
    exerciseType: "Compound",
    instructions: "Hold a medicine ball at chest height, squat down, then stand explosively and throw the ball up to a target on the wall, catching it and repeating.",
    commonMistakes: "Not squatting deep enough, catching the ball with straight arms.",
    tips: "Let your legs generate most of the power for the throw, not just your arms.",
  },

  // ============================================================
  // CARDIO
  // ============================================================
  {
    name: "Treadmill Running",
    muscleGroup: "Cardio",
    secondaryMuscles: ["Legs", "Core"],
    equipment: "Other",
    difficulty: "Beginner",
    exerciseType: "Compound",
    instructions: "Run at a steady pace on the treadmill, maintaining an upright posture and consistent stride, for your chosen duration or distance.",
    commonMistakes: "Overstriding, leaning too far forward or backward.",
    tips: "Land with your foot beneath your hips rather than reaching out in front of you.",
  },
  {
    name: "Jump Rope",
    muscleGroup: "Cardio",
    secondaryMuscles: ["Legs", "Forearms"],
    equipment: "Other",
    difficulty: "Beginner",
    exerciseType: "Compound",
    instructions: "Hold the rope handles at hip height, swing it over your head and jump just high enough to clear it with each rotation.",
    commonMistakes: "Jumping too high, using the whole arm to swing rather than the wrists.",
    tips: "Stay light on your feet and keep jumps small and controlled.",
  },
  {
    name: "Rowing Machine",
    muscleGroup: "Cardio",
    secondaryMuscles: ["Back", "Legs", "Biceps"],
    equipment: "Machine",
    difficulty: "Beginner",
    exerciseType: "Compound",
    instructions: "Drive through your legs first, then lean back slightly and pull the handle to your torso, reversing the sequence to return.",
    commonMistakes: "Pulling with the arms before the legs finish driving, rounding the back at the catch.",
    tips: "Think 'legs, body, arms' on the drive and reverse the order on the return.",
  },
  {
    name: "Stationary Cycling",
    muscleGroup: "Cardio",
    secondaryMuscles: ["Legs"],
    equipment: "Machine",
    difficulty: "Beginner",
    exerciseType: "Compound",
    instructions: "Set an appropriate seat height and resistance, then pedal at a steady or interval pace for your chosen duration.",
    commonMistakes: "Seat set too low, causing excess knee strain.",
    tips: "Your knee should have a slight bend at the bottom of each pedal stroke.",
  },
  {
    name: "Stair Climber",
    muscleGroup: "Cardio",
    secondaryMuscles: ["Legs", "Glutes"],
    equipment: "Machine",
    difficulty: "Beginner",
    exerciseType: "Compound",
    instructions: "Step continuously on the machine's pedals at a steady pace, keeping your posture upright and avoiding leaning on the handles.",
    commonMistakes: "Leaning heavily on the side rails, taking short shuffling steps.",
    tips: "Take full steps and let your legs do the work instead of your arms.",
  },
  {
    name: "Elliptical Trainer",
    muscleGroup: "Cardio",
    secondaryMuscles: ["Legs", "Shoulders"],
    equipment: "Machine",
    difficulty: "Beginner",
    exerciseType: "Compound",
    instructions: "Stand on the pedals holding the moving handles, pedal in a smooth elliptical motion at a steady pace.",
    commonMistakes: "Relying only on momentum rather than actively pushing and pulling the handles.",
    tips: "Engage your arms with the moving handles for a fuller-body workout.",
  },
  {
    name: "Battle Ropes",
    muscleGroup: "Cardio",
    secondaryMuscles: ["Shoulders", "Core", "Forearms"],
    equipment: "Other",
    difficulty: "Intermediate",
    exerciseType: "Compound",
    instructions: "Holding one end of the rope in each hand, whip them up and down alternately or together in waves for a set duration.",
    commonMistakes: "Standing too upright without engaging the legs and core.",
    tips: "Bend your knees slightly and stay athletic through the whole set.",
  },
  {
    name: "Sled Push",
    muscleGroup: "Cardio",
    secondaryMuscles: ["Legs", "Core", "Shoulders"],
    equipment: "Other",
    difficulty: "Intermediate",
    exerciseType: "Compound",
    instructions: "Grip the sled handles, lean forward, and drive your legs to push the sled forward for a set distance.",
    commonMistakes: "Standing too upright, taking short choppy steps.",
    tips: "Keep a consistent forward lean and drive through the balls of your feet.",
  },
];

const run = async () => {
  const mongoUri = process.env.MONGO_URI;

  if (!mongoUri) {
    console.error(
      "MONGO_URI is not set. Add it to your .env file (or rename this check to match your env var).",
    );
    process.exit(1);
  }

  await mongoose.connect(mongoUri);
  console.log("Connected to MongoDB.");

  const fresh = process.argv.includes("--fresh");

  if (fresh) {
    const { deletedCount } = await Exercise.deleteMany({});
    console.log(`--fresh flag set: removed ${deletedCount} existing exercise(s).`);
  }

  let created = 0;
  let updated = 0;

  for (const exercise of exercises) {
    const result = await Exercise.findOneAndUpdate(
      { name: exercise.name },
      { $set: exercise },
      { upsert: true, new: true, rawResult: true },
    );

    if (result.lastErrorObject?.updatedExisting) {
      updated += 1;
    } else {
      created += 1;
    }
  }

  console.log(`Seed complete. Created: ${created}, Updated: ${updated}, Total in file: ${exercises.length}`);

  await mongoose.disconnect();
  process.exit(0);
};

run().catch((error) => {
  console.error("Seeding failed:", error);
  process.exit(1);
});